name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd ~/bithama/bithama_future_trade
            git pull origin main

            # 백엔드 빌드
            cd backend
            npm install
            npx prisma migrate deploy  # ← 추가
            npm run build
            pm2 restart bithama-backend

            # 프론트 빌드
            cd ../frontend
            npm install
            npm run build
            pm2 restart bithama-frontend
